### ISSUE TITLE
OTF and TTF versions of Albert Sans (v1.3) lead to different line spacing in Word for Windows

### ISSUE THREAD

**Issue by HolgerGerhardt** [usted/Albert-Sans#5] opened 2024-07-27 22:14 UTC
The line spacing of the OTF version is substantially larger than that of the TTF version in Word (Microsoft 365, current version) for Windows (11):

**TTF version:**

<img width="770" alt="TTF" src="https://github.com/user-attachments/assets/cab651f3-f06e-41da-a5bb-74c397e92c2a">

**OTF version:**

<img width="782" alt="OTF" src="https://github.com/user-attachments/assets/c03abd40-7933-4cae-8d44-0b525ddae9a5">

This can be very annoying when collaborating with others on a document or when editing the document on different computers, since one has to make sure that the same font format is used on all machines.

**Comment by kenmcd** [comment] 2024-07-28 18:24
This is a problem in Word, not in the fonts.
Line spacing of 1, or 1.15, or 2, etc. does not work.
The work-around is to use a fixed line height, in points. 
This is due to the bizarre way Word calculates line height.

Try it with other fonts. You will see the same thing.
The problem is not the fonts.

**Comment by HolgerGerhardt** [comment] 2024-07-28 19:08
I can certainly imagine that Word plays a role in this. However, the font files do seem to have an influence, too:

I just tested this using the OTF and TTF versions of Source Serif 4 (https://github.com/adobe-fonts/source-serif/releases/tag/4.005R) and of Inter v4 (https://rsms.me/inter/download/). At least these two typefaces have identical line heights for the OTF and TTF versions.

**Comment by usted** [comment] 2024-07-30 20:28
This is a strange issue that is due to mac os system. It can be fixed by including The STAT table in the font files. Unfortunately GF ignores that tag and doesn't include it. So to make a Long story short: i have fixed The issue by lowering The height of The accents.
So it's fixed in The new release. 
Thank you both.

**Closed as completed** 2024-07-30 20:29 UTC

**Comment by HolgerGerhardt** [comment] 2024-07-31 05:47
I have just tried the current version of Albert Sans. Unfortunately, the issue still exists:

TTF:
<img width="1030" alt="TTF" src="https://github.com/user-attachments/assets/06fd1355-5e5f-4b03-b13c-417ad281dccc">

OTF:
<img width="1041" alt="OTF" src="https://github.com/user-attachments/assets/5f86165c-621d-4085-8261-e3bacad826f1">

> This is a strange issue that is due to mac os system.

Please note that my bug report concerned **Word for Windows**, not macOS.
